batch_size: 128
epochs: 300
lr: 0.0001

device: cuda:0
num_workers: 8 #4
seed: 1234
use_wandb: False

data_dir: data

# Evaluation
model_path: 

# Regularization
weight_decay: 0.000  # L2正則化項の重み #change  add

lambda_domain: 0.0  # ここに追加